### PR TITLE
android echo bug

### PR DESCRIPTION
**Pull request by consumadevtek**
android echo fix

### CODE REVIEW

**Review by zxcpoiu — CHANGES_REQUESTED** [review]
Could you describe what exactly the problem is, and, how this solves it?
( The expected behavior and the actual behavior )

**Comment by saif-o99** [comment]
hey @zxcpoiu . did you solve the echo bug without thie PR? is this not needed?

**Comment by zxcpoiu** [comment]
@saif-o99 

My case is always use `start()` first, so the audio mode is always `MODE_IN_COMMUNICATION`
for more detail, see: https://github.com/react-native-webrtc/react-native-incall-manager/pull/201#issuecomment-1338117571

**Comment by zxcpoiu** [comment]
closed in favor of #201

**Pull request closed without merging**
